### ISSUE TITLE
Variante da aplicação

### ISSUE THREAD

**Issue by GNakayama** [GNakayama/INE5413#3]
Faça uma variante do programa onde antes de ocorrer uma chamada de emergência o programa vai adicionar um valor aleatório diferente ao custo de cada uma das arestas e então realizar o cálculo, anote o tempo que o programa leva para grafos com 10, 15 e 20 vertíces, e um número compátivel de arestas, e responda a seguinte pergunta:

- É viável utilizar-se floyd para solução de problemas em tempo real onde não é possível a priore calcular a matriz de roteamento?

**Comment by rodolfolottin** [comment]
Faltando apenas retorno do tempo para o cálculo
